

Speakerboxxx/The Love Below

['https://genius.com/Big-boi-intro-speakerboxxx-lyrics',
'https://genius.com/Outkast-ghettomusick-lyrics',
'https://genius.com/Big-boi-unhappy-lyrics',
'https://genius.com/Big-boi-bowtie-lyrics',
'https://genius.com/Big-boi-the-way-you-move-lyrics',
'https://genius.com/Big-boi-the-rooster-lyrics',
'https://genius.com/Big-boi-bust-lyrics',
'https://genius.com/Big-boi-war-lyrics',
'https://genius.com/Big-boi-church-lyrics',
'https://genius.com/Big-boi-bamboo-interlude-lyrics',
'https://genius.com/Big-boi-tomb-of-the-boom-lyrics',
'https://genius.com/Big-boi-e-mac-interlude-lyrics',
'https://genius.com/Outkast-knowing-lyrics',
'https://genius.com/Big-boi-flip-flop-rock-lyrics',
'https://genius.com/Big-boi-interlude-lyrics',
'https://genius.com/Big-boi-reset-lyrics',
'https://genius.com/Big-boi-d-boi-interlude-lyrics',
'https://genius.com/Big-boi-last-call-lyrics',
'https://genius.com/Big-boi-bowtie-postlude-lyrics',
'https://genius.com/Andre-3000-the-love-below-intro-lyrics',
'https://genius.com/Andre-3000-love-hater-lyrics',
'https://genius.com/Andre-3000-god-interlude-lyrics',
'https://genius.com/Andre-3000-happy-valentines-day-lyrics',
'https://genius.com/Andre-3000-spread-lyrics',
'https://genius.com/Andre-3000-where-are-my-panties-interlude-lyrics',
'https://genius.com/Andre-3000-prototype-lyrics',
'https://genius.com/Andre-3000-she-lives-in-my-lap-lyrics',
'https://genius.com/Outkast-hey-ya-lyrics',
'https://genius.com/Outkast-roses-lyrics',
'https://genius.com/Andre-3000-good-day-good-sir-interlude-lyrics',
'https://genius.com/Andre-3000-behold-a-lady-lyrics',
'https://genius.com/Outkast-pink-and-blue-lyrics',
'https://genius.com/Andre-3000-love-in-war-lyrics',
'https://genius.com/Andre-3000-shes-alive-lyrics',
'https://genius.com/Andre-3000-draculas-wedding-lyrics',
'https://genius.com/Andre-3000-the-letter-interlude-lyrics',
'https://genius.com/Andre-3000-my-favorite-things-lyrics',
'https://genius.com/Andre-3000-take-off-your-cool-lyrics',
'https://genius.com/Andre-3000-vibrate-lyrics',
'https://genius.com/Andre-3000-a-life-in-the-day-of-benjamin-andre-incomplete-lyrics']

The Score

['https://genius.com/Fugees-red-intro-lyrics',
'https://genius.com/Fugees-how-many-mics-lyrics',
'https://genius.com/Fugees-ready-or-not-lyrics',
'https://genius.com/Fugees-zealots-lyrics',
'https://genius.com/Fugees-the-beast-lyrics',
'https://genius.com/Fugees-fu-gee-la-lyrics',
'https://genius.com/Fugees-family-business-lyrics',
'https://genius.com/Fugees-killing-me-softly-lyrics',
'https://genius.com/Fugees-the-score-lyrics',
'https://genius.com/Fugees-the-mask-lyrics',
'https://genius.com/Fugees-the-mask-lyrics',
'https://genius.com/Fugees-cowboys-lyrics',
'https://genius.com/Fugees-no-woman-no-cry-lyrics',
'https://genius.com/Fugees-manifest-outro-lyrics',
'https://genius.com/Fugees-fu-gee-la-refugee-camp-remix-lyrics',
'https://genius.com/Fugees-fu-gee-la-sly-and-robbie-remix-lyrics',
'https://genius.com/Fugees-mista-mista-lyrics',
'https://genius.com/Fugees-chinese-restaurant-skit-lyrics']

The Blueprint

['https://genius.com/Jay-z-the-rulers-back-lyrics',
'https://genius.com/Jay-z-takeover-lyrics',
'https://genius.com/Jay-z-izzo-hova-lyrics',
'https://genius.com/Jay-z-girls-girls-girls-lyrics',
'https://genius.com/Jay-z-jigga-that-nigga-lyrics',
'https://genius.com/Jay-z-u-dont-know-lyrics',
'https://genius.com/Jay-z-hola-hovito-lyrics',
'https://genius.com/Jay-z-heart-of-the-city-aint-no-love-lyrics',
'https://genius.com/Jay-z-never-change-lyrics',
'https://genius.com/Jay-z-song-cry-lyrics',
'https://genius.com/Jay-z-all-i-need-lyrics',
'https://genius.com/Jay-z-renegade-lyrics',
'https://genius.com/Jay-z-blueprint-momma-loves-me-lyrics',
'https://genius.com/Jay-z-breathe-easy-lyrical-exercise-lyrics',
'https://genius.com/Jay-z-girls-girls-girls-pt-2-lyrics']


Enter the Wu-Tang (36 Chambers)

['https://genius.com/Wu-tang-clan-bring-da-ruckus-lyrics',
'https://genius.com/Wu-tang-clan-shame-on-a-nigga-lyrics',
'https://genius.com/Wu-tang-clan-clan-in-da-front-lyrics',
'https://genius.com/Wu-tang-clan-wu-tang-7th-chamber-lyrics',
'https://genius.com/Wu-tang-clan-can-it-be-all-so-simple-intermission-lyrics',
'https://genius.com/Wu-tang-clan-da-mystery-of-chessboxin-lyrics',
'https://genius.com/Wu-tang-clan-wu-tang-clan-aint-nuthing-ta-fuck-wit-lyrics',
'https://genius.com/Wu-tang-clan-cream-lyrics',
'https://genius.com/Wu-tang-clan-method-man-lyrics',
'https://genius.com/Wu-tang-clan-protect-ya-neck-lyrics',
'https://genius.com/Wu-tang-clan-tearz-lyrics',
'https://genius.com/Wu-tang-clan-wu-tang-7th-chamber-pt-ii-lyrics',
'https://genius.com/Wu-tang-clan-conclusion-lyrics']

Raising Hell

['https://genius.com/Run-dmc-peter-piper-lyrics',
'https://genius.com/Run-dmc-its-tricky-lyrics',
'https://genius.com/Run-dmc-my-adidas-lyrics',
'https://genius.com/Run-dmc-walk-this-way-lyrics',
'https://genius.com/Run-dmc-is-it-live-lyrics',
'https://genius.com/Run-dmc-perfection-lyrics',
'https://genius.com/Run-dmc-hit-it-run-lyrics',
'https://genius.com/Run-dmc-raising-hell-lyrics',
'https://genius.com/Run-dmc-you-be-illin-lyrics',
'https://genius.com/Run-dmc-dumb-girl-lyrics',
'https://genius.com/Run-dmc-son-of-byford-lyrics',
'https://genius.com/Run-dmc-proud-to-be-black-lyrics',
'https://genius.com/Run-dmc-lord-of-lyrics-demo-lyrics',
'https://genius.com/Run-dmc-raising-hell-radio-tour-spot-lyrics',
'https://genius.com/Run-dmc-live-at-the-apollo-raw-vocal-lyrics']

Doggystyle

['https://genius.com/Snoop-dogg-bathtub-lyrics',
'https://genius.com/Snoop-dogg-g-funk-intro-lyrics',
'https://genius.com/Snoop-dogg-gin-and-juice-lyrics',
'https://genius.com/Snoop-dogg-w-balls-lyrics',
'https://genius.com/Snoop-dogg-tha-shiznit-lyrics',
'https://genius.com/Snoop-dogg-house-party-lyrics',
'https://genius.com/Snoop-dogg-lodi-dodi-lyrics',
'https://genius.com/Snoop-dogg-murder-was-the-case-death-after-visualizing-eternity-lyrics',
'https://genius.com/Snoop-dogg-serial-killa-lyrics',
'https://genius.com/Snoop-dogg-who-am-i-whats-my-name-lyrics',
'https://genius.com/Snoop-dogg-for-all-my-niggaz-and-bitches-lyrics',
'https://genius.com/Snoop-dogg-aint-no-fun-if-the-homies-cant-have-none-lyrics',
'https://genius.com/Snoop-dogg-chronic-break-lyrics',
'https://genius.com/Snoop-dogg-doggy-dogg-world-lyrics',
'https://genius.com/Snoop-dogg-class-room-intro-lyrics',
'https://genius.com/Snoop-dogg-gz-and-hustlas-lyrics',
'https://genius.com/Snoop-dogg-checkin-lyrics',
'https://genius.com/Snoop-dogg-gz-up-hoes-down-lyrics',
'https://genius.com/Snoop-dogg-pump-pump-lyrics']

8 Mile

['https://genius.com/Eminem-lose-yourself-lyrics',
'https://genius.com/Eminem-love-me-lyrics',
'https://genius.com/Eminem-8-mile-lyrics',
'https://genius.com/Obie-trice-adrenaline-rush-lyrics',
'https://genius.com/50-cent-places-to-go-lyrics',
'https://genius.com/D12-rap-game-lyrics',
'https://genius.com/Jay-z-8-miles-and-runnin-lyrics',
'https://genius.com/Xzibit-spit-shine-lyrics',
'https://genius.com/Macy-gray-time-of-my-life-lyrics',
'https://genius.com/Nas-u-wanna-be-me-lyrics',
'https://genius.com/50-cent-wanksta-lyrics',
'https://genius.com/Boomkat-wasting-my-time-lyrics',
'https://genius.com/Rakim-rakim-lyrics',
'https://genius.com/Young-zee-thats-my-nigga-fo-real-lyrics',
'https://genius.com/Gang-starr-battle-lyrics',
'https://genius.com/Eminem-rabbit-run-lyrics',
'https://genius.com/Obie-trice-rap-name-lyrics',
'https://genius.com/Eminem-stimulate-lyrics',
'https://genius.com/50-cent-till-i-collapse-freestyle-lyrics',
'https://genius.com/Joe-beast-gangsta-lyrics',
'https://genius.com/Brooklyn-the-weekend-lyrics',
'https://genius.com/Shaunta-california-lyrics']

The Black Album

['https://genius.com/Jay-z-interlude-lyrics',
'https://genius.com/Jay-z-december-4th-lyrics',
'https://genius.com/Jay-z-what-more-can-i-say-lyrics',
'https://genius.com/Jay-z-encore-lyrics',
'https://genius.com/Jay-z-change-clothes-lyrics',
'https://genius.com/Jay-z-dirt-off-your-shoulder-lyrics',
'https://genius.com/Jay-z-threat-lyrics',
'https://genius.com/Jay-z-moment-of-clarity-lyrics',
'https://genius.com/Jay-z-99-problems-lyrics',
'https://genius.com/Jay-z-public-service-announcement-lyrics',
'https://genius.com/Jay-z-justify-my-thug-lyrics',
'https://genius.com/Jay-z-lucifer-lyrics',
'https://genius.com/Jay-z-allure-lyrics',
'https://genius.com/Jay-z-my-1st-song-lyrics']

No Way Out

['https://genius.com/Diddy-no-way-out-intro-lyrics',
'https://genius.com/Diddy-victory-lyrics',
'https://genius.com/Diddy-been-around-the-world-lyrics',
'https://genius.com/Diddy-what-you-gonna-do-lyrics',
'https://genius.com/Diddy-dont-stop-what-youre-doing-lyrics',
'https://genius.com/Diddy-if-i-should-die-tonight-interlude-lyrics',
'https://genius.com/Diddy-do-you-know-lyrics',
'https://genius.com/Diddy-young-gs-lyrics',
'https://genius.com/Diddy-i-love-you-baby-lyrics',
'https://genius.com/Puff-daddy-and-the-family-its-all-about-the-benjamins-remix-lyrics',
'https://genius.com/Diddy-pain-lyrics',
'https://genius.com/Diddy-is-this-the-end-lyrics',
'https://genius.com/Diddy-i-got-the-power-lyrics',
'https://genius.com/Diddy-friends-lyrics',
'https://genius.com/Diddy-senorita-lyrics',
'https://genius.com/Diddy-ill-be-missing-you-lyrics',
'https://genius.com/Diddy-cant-nobody-hold-me-down-lyrics']

The Blueprint 3

['https://genius.com/Jay-z-what-we-talkin-about-lyrics',
'https://genius.com/Jay-z-thank-you-lyrics',
'https://genius.com/Jay-z-doa-death-of-auto-tune-lyrics',
'https://genius.com/Jay-z-run-this-town-lyrics',
'https://genius.com/Jay-z-empire-state-of-mind-lyrics',
'https://genius.com/Jay-z-real-as-it-gets-lyrics',
'https://genius.com/Jay-z-on-to-the-next-one-lyrics',
'https://genius.com/Jay-z-off-that-lyrics',
'https://genius.com/Jay-z-a-star-is-born-lyrics',
'https://genius.com/Jay-z-venus-vs-mars-lyrics',
'https://genius.com/Jay-z-already-home-lyrics',
'https://genius.com/Jay-z-hate-lyrics',
'https://genius.com/Jay-z-reminder-lyrics',
'https://genius.com/Jay-z-so-ambitious-lyrics',
'https://genius.com/Jay-z-young-forever-lyrics']

Reasonable Doubt

['https://genius.com/Jay-z-cant-knock-the-hustle-lyrics',
'https://genius.com/Jay-z-politics-as-usual-lyrics',
'https://genius.com/Jay-z-brooklyns-finest-lyrics',
'https://genius.com/Jay-z-dead-presidents-ii-lyrics',
'https://genius.com/Jay-z-feelin-it-lyrics',
'https://genius.com/Jay-z-devils-lyrics',
'https://genius.com/Jay-z-22-twos-lyrics',
'https://genius.com/Jay-z-can-i-live-lyrics',
'https://genius.com/Jay-z-aint-no-nigga-lyrics',
'https://genius.com/Jay-z-friend-or-foe-lyrics',
'https://genius.com/Jay-z-coming-of-age-lyrics',
'https://genius.com/Jay-z-cashmere-thoughts-lyrics',
'https://genius.com/Jay-z-bring-it-on-lyrics',
'https://genius.com/Jay-z-regrets-lyrics',
'https://genius.com/Jay-z-cant-knock-the-hustle-fools-paradise-remix-lyrics',
'https://genius.com/Jay-z-can-i-live-ii-lyrics']

Vol. 2…Hard Knock Life

['https://genius.com/Jay-z-intro-hand-it-down-lyrics',
'https://genius.com/Jay-z-hard-knock-life-ghetto-anthem-lyrics',
'https://genius.com/Jay-z-if-i-should-die-lyrics',
'https://genius.com/Jay-z-ride-or-die-lyrics',
'https://genius.com/Jay-z-nigga-what-nigga-who-originator-99-lyrics',
'https://genius.com/Jay-z-money-cash-hoes-lyrics',
'https://genius.com/Jay-z-a-week-ago-lyrics',
'https://genius.com/Jay-z-coming-of-age-da-sequel-lyrics',
'https://genius.com/Jay-z-can-i-get-a-lyrics',
'https://genius.com/Jay-z-paper-chase-lyrics',
'https://genius.com/Jay-z-reservoir-dogs-lyrics',
'https://genius.com/Jay-z-its-like-that-lyrics',
'https://genius.com/Jay-z-its-alright-lyrics',
'https://genius.com/Jermaine-dupri-money-aint-a-thang-lyrics']

Supa Dupa Fly

['https://genius.com/Missy-elliott-bustas-intro-lyrics',
'https://genius.com/Missy-elliott-hit-em-wit-da-hee-lyrics',
'https://genius.com/Missy-elliott-sock-it-2-me-lyrics',
'https://genius.com/Missy-elliott-the-rain-supa-dupa-fly-lyrics',
'https://genius.com/Missy-elliott-beep-me-911-lyrics',
'https://genius.com/Missy-elliott-they-dont-wanna-fuck-wit-me-lyrics',
'https://genius.com/Missy-elliott-pass-da-blunt-lyrics',
'https://genius.com/Missy-elliott-bite-our-style-interlude-lyrics',
'https://genius.com/Missy-elliott-friendly-skies-lyrics',
'https://genius.com/Missy-elliott-best-friends-lyrics',
'https://genius.com/Missy-elliott-dont-be-commin-in-my-face-lyrics',
'https://genius.com/Missy-elliott-izzy-izzy-ahh-lyrics',
'https://genius.com/Missy-elliott-why-you-hurt-me-lyrics',
'https://genius.com/Missy-elliott-im-talkin-lyrics',
'https://genius.com/Missy-elliott-gettaway-lyrics',
'https://genius.com/Missy-elliott-bustas-outro-lyrics',
'https://genius.com/Missy-elliott-missys-finale-lyrics']

E. 1999 Eternal

['https://genius.com/Bone-thugs-n-harmony-da-introduction-lyrics',
'https://genius.com/Bone-thugs-n-harmony-east-1999-lyrics',
'https://genius.com/Bone-thugs-n-harmony-eternal-lyrics',
'https://genius.com/Bone-thugs-n-harmony-crept-and-we-came-lyrics',
'https://genius.com/Bone-thugs-n-harmony-down-71-the-getaway-lyrics',
'https://genius.com/Bone-thugs-n-harmony-mr-bill-collector-lyrics',
'https://genius.com/Bone-thugs-n-harmony-budsmokers-only-lyrics',
'https://genius.com/Bone-thugs-n-harmony-tha-crossroads-dj-u-neeks-mo-thug-remix-lyrics',
'https://genius.com/Bone-thugs-n-harmony-me-killa-lyrics',
'https://genius.com/Bone-thugs-n-harmony-land-of-tha-heartless-lyrics',
'https://genius.com/Bone-thugs-n-harmony-no-shorts-no-losses-lyrics',
'https://genius.com/Bone-thugs-n-harmony-1st-of-tha-month-lyrics',
'https://genius.com/Bone-thugs-n-harmony-buddah-lovaz-lyrics',
'https://genius.com/Bone-thugs-n-harmony-die-die-die-lyrics',
'https://genius.com/Bone-thugs-n-harmony-mr-ouija-2-lyrics',
'https://genius.com/Bone-thugs-n-harmony-mo-murda-lyrics',
'https://genius.com/Bone-thugs-n-harmony-shotz-to-tha-double-glock-lyrics']

He’s the DJ, I’m the Rapper

['https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-a-nightmare-on-my-street-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-here-we-go-again-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-brand-new-funk-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-time-to-chill-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-charlie-mack-the-first-out-the-limo-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-as-we-go-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-parents-just-dont-understand-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-pump-up-the-bass-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-lets-get-busy-baby-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-live-at-union-square-november-1986-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-dj-on-wheels-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-my-buddy-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-rhythm-trax-house-party-style-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-hes-the-dj-im-the-rapper-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-hip-hop-dancers-theme-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-jazzys-in-the-house-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-human-video-game-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-another-special-announcement-lyrics',
'https://genius.com/Dj-jazzy-jeff-and-the-fresh-prince-nightmare-on-my-street-single-version-lyrics']

The Don illuminati – The 7 Day Theory

['https://genius.com/2pac-bomb-first-my-second-reply-lyrics',
'https://genius.com/2pac-hail-mary-lyrics',
'https://genius.com/2pac-toss-it-up-lyrics',
'https://genius.com/2pac-to-live-and-die-in-la-lyrics',
'https://genius.com/2pac-blasphemy-lyrics',
'https://genius.com/2pac-life-of-an-outlaw-lyrics',
'https://genius.com/2pac-just-like-daddy-lyrics',
'https://genius.com/2pac-krazy-lyrics',
'https://genius.com/2pac-white-manz-world-lyrics',
'https://genius.com/2pac-me-and-my-girlfriend-lyrics',
'https://genius.com/2pac-hold-ya-head-lyrics',
'https://genius.com/2pac-against-all-odds-lyrics']

Wu-Tang Forever

['https://genius.com/Wu-tang-clan-wu-revolution-lyrics',
'https://genius.com/Wu-tang-clan-reunited-lyrics',
'https://genius.com/Wu-tang-clan-for-heavens-sake-lyrics',
'https://genius.com/Wu-tang-clan-cash-still-rules-scary-hours-still-dont-nothing-move-but-the-money-lyrics',
'https://genius.com/Wu-tang-clan-visionz-lyrics',
'https://genius.com/Wu-tang-clan-as-high-as-wu-tang-get-lyrics',
'https://genius.com/Wu-tang-clan-severe-punishment-lyrics',
'https://genius.com/Wu-tang-clan-older-gods-lyrics',
'https://genius.com/Wu-tang-clan-maria-lyrics',
'https://genius.com/Wu-tang-clan-a-better-tomorrow-lyrics',
'https://genius.com/Wu-tang-clan-its-yourz-lyrics',
'https://genius.com/Wu-tang-clan-wu-tang-forever-intro-lyrics',
'https://genius.com/Wu-tang-clan-triumph-lyrics',
'https://genius.com/Wu-tang-clan-impossible-lyrics',
'https://genius.com/Wu-tang-clan-little-ghetto-boys-lyrics',
'https://genius.com/Wu-tang-clan-deadly-melody-lyrics',
'https://genius.com/Wu-tang-clan-the-city-lyrics',
'https://genius.com/Wu-tang-clan-the-projects-lyrics',
'https://genius.com/Wu-tang-clan-bells-of-war-lyrics',
'https://genius.com/Wu-tang-clan-the-mgm-lyrics',
'https://genius.com/Wu-tang-clan-dog-shit-lyrics',
'https://genius.com/Wu-tang-clan-duck-seazon-lyrics',
'https://genius.com/Wu-tang-clan-hellz-wind-staff-lyrics',
'https://genius.com/Wu-tang-clan-heaterz-lyrics',
'https://genius.com/Wu-tang-clan-black-shampoo-lyrics',
'https://genius.com/Wu-tang-clan-second-coming-lyrics',
'https://genius.com/Wu-tang-clan-the-closing-lyrics',
'https://genius.com/Wu-tang-clan-sunshower-lyrics',
'https://genius.com/Wu-tang-clan-projects-international-remix-lyrics',
'https://genius.com/Wu-tang-clan-triumph-video-version-lyrics']